# Generated by Django 4.1.4 on 2023-06-20 08:13

from django.db import migrations, models

#When migration are made this file is created and the table contact 
#after creating the table make migrations using the command python manage.py makemigrations and migrate
#the register this into the admin in ecommerce ap to show at the backend administration
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField(max_length=500)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
